# Grilla de colores

Se tiene una grilla de cuadrados de 9×9, cada uno comienza pintado aleatoriamente de rojo o azul. 

<img src="grilla.jpg" width="200">
Se quiere pintar algunos cuadrados de manera que si se divide la grilla total en sub-grillas de 3x3 cada una de estas sub-grillas contenga cuadrados del mismo color pero el color de cada sub-grilla sea diferente que el de las subgrillas adyacentes.
<img src="grilla-solucion-1.jpg" width="200"><img src="grilla-solucion-2.jpg" width="200" >
Resolver el problema de manera que no sea necesario pintar un cuadrado más de una vez y se pinte la cantidad mínima de cuadrados




In [28]:
import numpy as np

solution1 = np.array([
        [0, 0, 0, 1, 1, 1, 0, 0, 0], [0, 0, 0, 1, 1, 1, 0, 0, 0], [0, 0, 0, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 0, 0, 0, 1, 1, 1], [1, 1, 1, 0, 0, 0, 1, 1, 1], [1, 1, 1, 0, 0, 0, 1, 1, 1],
        [0, 0, 0, 1, 1, 1, 0, 0, 0], [0, 0, 0, 1, 1, 1, 0, 0, 0], [0, 0, 0, 1, 1, 1, 0, 0, 0],
    ])
solution2 = np.array([
        [1, 1, 1, 0, 0, 0, 1, 1, 1], [1, 1, 1, 0, 0, 0, 1, 1, 1], [1, 1, 1, 0, 0, 0, 1, 1, 1],
        [0, 0, 0, 1, 1, 1, 0, 0, 0], [0, 0, 0, 1, 1, 1, 0, 0, 0], [0, 0, 0, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 0, 0, 0, 1, 1, 1], [1, 1, 1, 0, 0, 0, 1, 1, 1], [1, 1, 1, 0, 0, 0, 1, 1, 1],
    ])
            
def Solution(c_s1, c_s2):
    if c_s1 < c_s2:
        solution = solution1
        print("Se elige la solución 1\n")
    else:
        solution = solution2
        print("Se elige la solución 2\n")
    return solution

def pintadas(matrix, painted):
    print(matrix)
    print(f'\nCantidad Pintadas: {painted}')
    
def main(solution1,solution2):
    
    matrix = np.random.randint(0, 2, (9, 9))
    c_s1 = 0
    c_s2 = 0
    painted = 0
    
    for x in range(0, matrix.shape[0]):
        for y in range(0, matrix.shape[1]):
            if matrix[x][y] != solution1[x][y]:
                c_s1 += 1
            if matrix[x][y] != solution2[x][y]:
                c_s2 += 1 
                
    solution = Solution(c_s1,c_s2)            
    
    for x in range(0, matrix.shape[0]):
        for y in range(0, matrix.shape[1]):
            if matrix[x][y] != solution[x][y]:
                matrix[x][y] = solution[x][y]
                painted += 1
        
    pintadas(matrix, painted)
    

if __name__ == '__main__':
    main(solution1, solution2)
    

Se elige la solución 2

[[1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]
 [1 1 1 0 0 0 1 1 1]]

Cantidad Pintadas: 40
